version: 4.3.1.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

skip_commits:
  files:
    - doc/**/*
    - docs/**/*
    - '**/*.html'

image:
  - Visual Studio 2017

build: off
test: off

artifacts:
  - path: artifacts/*.nupkg
    name: NuGet
  - path: artifacts/*.snupkg
    name: Symbols

build_script:
  - ps: .\Build.ps1

deploy:
- provider: NuGet
  name: Prerelease
  symbol_server: https://www.nuget.org
  artifact: NuGet, Symbols
  api_key:
    secure: OxGFtmO9BbWN4+be0SkCVwoRmwyES/Ve7k/wufyQfvG+dEZkaXSjKnnoolk9yktn
  on:
    branch: develop
- provider: NuGet
  name: Release
  symbol_server: https://www.nuget.org
  artifact: NuGet, Symbols
  api_key:
    secure: OxGFtmO9BbWN4+be0SkCVwoRmwyES/Ve7k/wufyQfvG+dEZkaXSjKnnoolk9yktn
  on:
    branch: master
